create table product
(
    product_id     bigint       not null
        primary key,
    description    varchar(255) null,
    name           varchar(255) null,
    fk_category_id bigint       null,
    fk_brand_id    bigint       null,
    constraint FKpxqa5fj6hpcc9mew356eoj68d
        foreign key (fk_category_id) references category (category_id),
    constraint product___fk_brand
        foreign key (fk_brand_id) references brand (brand_id)
);

INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (42, 'MacBook', 'Mac Book', 1, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (43, 'MacBook Pro', 'Mac Book Pro', 1, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (44, 'MacBook Mini', 'Mac Book Mini', 1, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (45, 'MacBook Lite', 'Mac Book Lite', 1, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (46, 'iPad', 'iPad', 1, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (47, 'iPad Pro', 'ipad Pro', 1, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (48, 'iPad Mini', 'iPad Mini', 1, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (49, 'Microsoft Surface', 'Microsoft Surface', 1, 2);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (50, 'Microsoft Surface Pro', 'Microsoft Surface Pro', 1, 2);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (51, 'Microsoft Surface Max', 'Microsoft Surface Max', 1, 2);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (52, 'Lenovo ThinkPad ', 'Lenovo ThinkPad ', 1, 13);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (53, 'Lenovo ThinkPad X', 'Lenovo ThinkPad X', 1, 13);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (54, 'Lenovo Yoga One', 'Lenovo Yoga One', 1, 13);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (55, 'Lenovo Yoga Two', 'Lenovo Yoga One', 1, 13);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (56, 'Dell Inspiron 14', 'Dell Inspiron 2014', 1, 12);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (57, 'Dell Inspiron 15', 'Dell Inspiron 2015', 1, 12);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (58, 'Dell Inspiron 16', 'Dell Inspiron 2016', 1, 12);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (59, 'XPS 13 Dell Business', 'XPS 13 Dell Business', 1, 12);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (60, 'XPS 14 Dell Business', 'XPS 14 Dell Business', 1, 12);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (1, 'apple iphone 1', 'iPhone1', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (2, 'apple iphone 2', 'iPhone2', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (3, 'apple iphone 3', 'iPhone3', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (4, 'apple iphone 4', 'iPhone4', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (5, 'apple iphone 5', 'iPhone5', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (6, 'apple iphone 6', 'iPhone6', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (7, 'apple iphone 7', 'iPhone7', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (8, 'apple iphone 8', 'iPhone8', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (9, 'apple iphone 9', 'iPhone9', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (10, 'apple iphone X', 'iPhoneX', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (11, 'apple iphone 11', 'iPhone11', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (12, 'apple iphone 12', 'iPhone12', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (14, 'mac book', 'MacBook', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (15, 'mac book pro', 'MacBook Pro', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (16, 'mac book mini', 'MacBook mini', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (17, 'iPad ', 'iPad', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (18, 'iPad Pro', 'iPad Pro', 2, 1);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (19, 'Pixel One', 'Pixel 1', 2, 3);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (20, 'Pixel Two', 'Pixel 2', 2, 3);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (21, 'Pixel Three', 'Pixel 3', 2, 3);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (22, 'Pixel Four', 'Pixel 4', 2, 3);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (23, 'Pixel Five', 'Pixel 5', 2, 3);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (24, 'Nokia Lumia ', 'Nokia Lumia', 2, 2);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (25, 'Nokia Lumia Pro', 'Nokia Lumia Pro', 2, 2);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (26, 'LG Awesome', 'LG Awesome', 2, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (27, 'LG Awesome Pro', 'LG Awesome Pro', 2, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (28, 'LG Awesome Max', 'LG Awesome Max', 2, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (29, 'LG Awesome Mini', 'LG Awesome Mini', 2, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (30, 'Sony Xperia One', 'Sony Xperia 1', 2, 7);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (31, 'Sony Xperia Two', 'Sony Xperia 2', 2, 7);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (32, 'Sony Xperia Three', 'Sony xperia 3', 2, 7);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (33, 'Sony Xperia Four', 'Sony Xperia 4', 2, 7);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (34, 'Sony Xperia Five', 'Sony Xperia 5', 2, 7);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (35, 'Local Farm Organic Onion', 'Onion', 3, 8);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (36, 'Local Farm Organic Tomato', 'Tomato', 3, 8);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (37, 'Local Farm Organic Potato', 'Potato', 3, 8);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (38, 'Local Farm Organic Chicken', 'Chicken', 3, 8);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (39, 'Local farm Organic Beef', 'Beef', 3, 8);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (40, 'Local Farm Organic Goat', 'Goat', 3, 8);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (41, 'Local Farm Organic Pork', 'Pork', 3, 8);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (61, 'Ohio Organic Pork', 'Pork', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (62, 'Ohio  Organic Goat', 'Goat', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (63, 'Ohio Organic Beef', 'Beef', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (64, 'Ohio Organic Chicken', 'Chicken', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (65, 'Ohio Organic Potato', 'Potato', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (66, 'Ohio Organic Tomato', 'Tomato', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (67, 'Ohio Organic Onion', 'Onion', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (68, 'Radish', 'Radish', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (69, 'Spanich', 'Spanich', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (70, 'Green Mustard ', 'Green Mustard ', 3, 9);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (71, 'Medicine 1', 'Medicine 1', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (72, 'Medicine 2', 'Medicine 2', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (73, 'Medicine 3', 'Medicine 3', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (74, 'Medicine 4', 'Medicine 4', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (75, 'Medicine 5', 'Medicine 5', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (76, 'Medicine 6', 'Medicine 6', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (77, 'Medicine 7', 'Medicine 7', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (78, 'Medicine 8', 'Medicine 8', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (79, 'Medicine 9', 'Medicine 9', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (80, 'Medicine 10', 'Medicine 10', 4, 14);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (81, 'Medicine Surgical 1', 'Medicine Surgical 1', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (82, 'Medicine Surgical 2', 'Medicine Surgical 2', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (83, 'Medicine Surgical 3', 'Medicine Surgical 3', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (84, 'Medicine Surgical 4', 'Medicine Surgical 4', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (85, 'Medicine Surgical 5', 'Medicine Surgical 5', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (86, 'Medicine Surgical 6', 'Medicine Surgical 6', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (87, 'Medicine Surgical 7', 'Medicine Surgical 7', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (88, 'Medicine Surgical 8', 'Medicine Surgical 8', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (89, 'Medicine Surgical 9', 'Medicine Surgical 9', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (90, 'Medicine Surgical 10', 'Medicine Surgical 10', 4, 15);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (91, 'Gap Mens Pants Skinny', 'Gap Mens Pants Skinny', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (92, 'Gap Mens Pants slim', 'Gap Mens Pants slim', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (93, 'Gap Mens Pants Straight', 'Gap Mens Pants Straight', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (94, 'Gap Mens Pants rough', 'Gap Mens Pants rough', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (95, 'Gap Mens Pants washed', 'Gap Mens Pants washed', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (96, 'Gap Mens T-shirts 2', 'Gap Mens T-shirts 2', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (97, 'Gap Mens T-shirts 1', 'Gap Mens T-shirts 1', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (98, 'Gap Mens T-shirts 3', 'Gap Mens T-shirts 3', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (99, 'Gap Mens T-shirts 4', 'Gap Mens T-shirts 4', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (100, 'Gap Mens T-shirts 5', 'Gap Mens T-shirts 5', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (101, 'Gap Women''s T-shirts 1', 'Gap Women''s T-shirts 1', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (102, 'Gap Women''s T-shirts 2', 'Gap Women''s T-shirts 2', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (103, 'Gap Women''s T-shirts 3', 'Gap Women''s T-shirts 3', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (104, 'Gap Women''s T-shirts 4', 'Gap Women''s T-shirts 4', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (105, 'Gap Women''s T-shirts 5', 'Gap Women''s T-shirts 5', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (106, 'Gap Women''s Hoodie ', 'Gap Women''s Hoodie ', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (107, 'Gap Women''s Hoodie ', 'Gap Women''s Hoodie ', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (108, 'Gap Men''s Hoodie ', 'Gap Men''s Hoodie ', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (109, 'Gap Mens''s Hoodie ', 'Gap Mens''s Hoodie ', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (110, 'Gap Women''s Bra ', 'Gap Women''s Bra ', 5, 10);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (111, 'Express Mens Pants Skinny', 'Express Mens Pants Skinny', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (112, 'Express Mens Pants slim', 'Express Mens Pants slim', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (113, 'Express Mens Pants Straight', 'Express Mens Pants Straight', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (114, 'Express Mens Pants rough', 'Express Mens Pants rough', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (115, 'Express Mens Pants washed', 'Express Mens Pants washed', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (116, 'Express Mens T-shirts 2', 'Express Mens T-shirts 2', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (117, 'Express Mens T-shirts 1', 'Express Mens T-shirts 1', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (118, 'Express Mens T-shirts 3', 'Express Mens T-shirts 3', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (119, 'Express Mens T-shirts 4', 'Express Mens T-shirts 4', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (120, 'Express Mens T-shirts 5', 'Express Mens T-shirts 5', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (121, 'Express Women''s T-shirts 1', 'Express Women''s T-shirts 1', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (122, 'Express Women''s T-shirts 2', 'Express Women''s T-shirts 2', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (123, 'Express Women''s T-shirts 3', 'Express Women''s T-shirts 3', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (124, 'Express Women''s T-shirts 4', 'Express Women''s T-shirts 4', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (125, 'Express Women''s T-shirts 5', 'Express Women''s T-shirts 5', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (126, 'Express Women''s Hoodie ', 'Express Women''s Hoodie ', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (127, 'Express Women''s Hoodie ', 'Express Women''s Hoodie ', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (128, 'Express Men''s Hoodie ', 'Express Men''s Hoodie ', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (129, 'Express Mens''s Hoodie ', 'Express Mens''s Hoodie ', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (130, 'Express Women''s Bra ', 'Express Women''s Bra ', 5, 16);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (131, 'Levi''s Mens Pants Skinny', 'Levi''s Mens Pants Skinny', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (132, 'Levi''s Mens Pants slim', 'Levi''s Mens Pants slim', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (133, 'Levi''s Mens Pants Straight', 'Levi''s Mens Pants Straight', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (134, 'Levi''s Mens Pants rough', 'Levi''s Mens Pants rough', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (135, 'Levi''s Mens Pants washed', 'Levi''s Mens Pants washed', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (136, 'Levi''s Mens T-shirts 2', 'Levi''s Mens T-shirts 2', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (137, 'Levi''s Mens T-shirts 1', 'Levi''s Mens T-shirts 1', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (138, 'Levi''s Mens T-shirts 3', 'Levi''s Mens T-shirts 3', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (139, 'Levi''s Mens T-shirts 4', 'Levi''s Mens T-shirts 4', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (140, 'Levi''s Mens T-shirts 5', 'Levi''s Mens T-shirts 5', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (141, 'Levi''s Women''s T-shirts 1', 'Levi''s Women''s T-shirts 1', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (142, 'Levi''s Women''s T-shirts 2', 'Levi''s Women''s T-shirts 2', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (143, 'Levi''s Women''s T-shirts 3', 'Levi''s Women''s T-shirts 3', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (144, 'Levi''s Women''s T-shirts 4', 'Levi''s Women''s T-shirts 4', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (145, 'Levi''s Women''s T-shirts 5', 'Levi''s Women''s T-shirts 5', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (146, 'Levi''s Women''s Hoodie ', 'Levi''s Women''s Hoodie ', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (147, 'Levi''s Women''s Hoodie ', 'Levi''s Women''s Hoodie ', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (148, 'Levi''s Men''s Hoodie ', 'Levi''s Men''s Hoodie ', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (149, 'Levi''s Mens''s Hoodie ', 'Levi''s Mens''s Hoodie ', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (150, 'Levi''s Women''s Bra ', 'Levi''s Women''s Bra ', 5, 17);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (151, 'American Eagle Mens Pants Skinny', 'American Eagle Mens Pants Skinny', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (152, 'American Eagle Mens Pants slim', 'American Eagle Mens Pants slim', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (153, 'American Eagle Mens Pants Straight', 'American Eagle Mens Pants Straight', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (154, 'American Eagle Mens Pants rough', 'American Eagle Mens Pants rough', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (155, 'American Eagle Mens Pants washed', 'American Eagle Mens Pants washed', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (156, 'American Eagle Mens T-shirts 2', 'American Eagle Mens T-shirts 2', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (157, 'American Eagle Mens T-shirts 1', 'American Eagle Mens T-shirts 1', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (158, 'American Eagle Mens T-shirts 3', 'American Eagle Mens T-shirts 3', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (159, 'American Eagle Mens T-shirts 4', 'American Eagle Mens T-shirts 4', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (160, 'American Eagle Mens T-shirts 5', 'American Eagle Mens T-shirts 5', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (161, 'American Eagle Women''s T-shirts 1', 'American Eagle Women''s T-shirts 1', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (162, 'American Eagle Women''s T-shirts 2', 'American Eagle Women''s T-shirts 2', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (163, 'American Eagle Women''s T-shirts 3', 'American Eagle Women''s T-shirts 3', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (164, 'American Eagle Women''s T-shirts 4', 'American Eagle Women''s T-shirts 4', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (165, 'American Eagle Women''s T-shirts 5', 'American Eagle Women''s T-shirts 5', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (166, 'American Eagle Women''s Hoodie ', 'American Eagle Women''s Hoodie ', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (167, 'American Eagle Women''s Hoodie ', 'American Eagle Women''s Hoodie ', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (168, 'American Eagle Men''s Hoodie ', 'American Eagle Men''s Hoodie ', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (169, 'American Eagle Mens''s Hoodie ', 'American Eagle Mens''s Hoodie ', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (170, 'American Eagle Women''s Bra ', 'American Eagle Women''s Bra ', 5, 18);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (171, 'Nike Air ', 'Nike Air ', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (172, 'Nike Air Pro', 'Nike Air Pro', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (173, 'Nike Air Max', 'Nike Air Max', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (174, 'Nike Succor', 'Nike Succor', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (175, 'Nike Basketball', 'Nike Basketball', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (176, 'Nike Running', 'Nike Running', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (177, 'Nike Daily', 'Nike Daily', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (178, 'Nike Golf', 'Nike Golf', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (179, 'Nike Tennis', 'Nike Tennis', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (180, 'Nike Track & Fields', 'Nike Track & Fields', 6, 19);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (181, 'Adidas Sneakers ', 'Adidas Sneakers ', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (182, 'Adidas Slides', 'Adidas Slides', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (183, 'Adidas Cleats', 'Adidas Cleats', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (184, 'Adidas High Tops', 'Adidas High Tops', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (185, 'Adidas Boots', 'Adidas Boots', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (186, 'Adidas Platform', 'Adidas Platform', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (187, 'Adidas Sandals', 'Adidas Sandals', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (188, 'Adidas Golf', 'Adidas Golf', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (189, 'Adidas Tennis', 'Adidas Tennis', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (190, 'Adidas Track & Fields', 'Adidas Track & Fields', 6, 20);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (191, 'Converse Sneakers ', 'Converse Sneakers ', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (192, 'Converse Slides', 'Converse Slides', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (193, 'Converse Low Tops', 'Converse Cleats', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (194, 'Converse High Tops', 'Converse High Tops', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (195, 'Converse Boots', 'Converse Boots', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (196, 'Converse Platform', 'Converse Platform', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (197, 'Converse Golf', 'Converse Golf', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (198, 'Converse Tennis', 'Converse Tennis', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (199, 'Converse Track & Fields', 'Converse Track & Fields', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (200, 'Converse Sandals', 'Converse Sandals', 6, 22);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (201, 'X Table', 'X Table', 7, 11);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (202, 'X Sofa', 'X Sofa', 7, 11);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (203, 'X Tea Table', 'X Tea Table', 7, 11);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (204, 'X TV Rack', 'X TV Rack', 7, 11);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (205, 'X Bed', 'X Bed', 7, 11);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (206, 'Canadian Table', 'Canadian Table', 7, 23);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (207, 'Canadian Sofa', 'Canadian Sofa', 7, 23);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (208, 'Canadian Tea Table', 'Canadian Tea Table', 7, 23);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (209, 'Canadian TV Rack', 'Canadian TV Rack', 7, 23);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (210, 'Canadian Bed', 'Canadian Bed', 7, 23);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (211, 'LG Refrigerator', 'LG Refrigerator', 8, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (212, 'LG Oven', 'LG Oven', 8, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (213, 'LG Dish Washer', 'LG Dish Washer', 8, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (214, 'LG Mixer', 'LG Mixer', 8, 6);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (215, 'Samsung Refrigerator', 'Samsung Refrigerator', 8, 24);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (216, 'Samsung Dish Washer', 'Samsung Dish Washer', 8, 24);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (217, 'Samsung Mixer', 'Samsung Mixer', 8, 24);
INSERT INTO online_shopping_inventory.product (product_id, description, name, fk_category_id, fk_brand_id) VALUES (218, 'Samsung Oven', 'Samsung Oven', 8, 24);